-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 64-Bit"
-- VERSION		"Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition"
-- CREATED		"Tue Oct 28 18:39:21 2025"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY multi_2b_cs IS 
	PORT
	(
		A0 :  IN  STD_LOGIC;
		B0 :  IN  STD_LOGIC;
		A1 :  IN  STD_LOGIC;
		B1 :  IN  STD_LOGIC;
		CK :  IN  STD_LOGIC;
		r0 :  OUT  STD_LOGIC;
		r1 :  OUT  STD_LOGIC;
		r2 :  OUT  STD_LOGIC;
		r3 :  OUT  STD_LOGIC;
		V1 :  OUT  STD_LOGIC;
		V2 :  OUT  STD_LOGIC
	);
END multi_2b_cs;

ARCHITECTURE bdf_type OF multi_2b_cs IS 

COMPONENT sumador_completo
	PORT(A : IN STD_LOGIC;
		 B : IN STD_LOGIC;
		 Cin : IN STD_LOGIC;
		 S : OUT STD_LOGIC;
		 Cout : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT band_c2
	PORT(Cout_2 : IN STD_LOGIC;
		 Cout_3 : IN STD_LOGIC;
		 A1 : IN STD_LOGIC;
		 B1 : IN STD_LOGIC;
		 r3 : IN STD_LOGIC;
		 V1 : OUT STD_LOGIC;
		 V2 : OUT STD_LOGIC
	);
END COMPONENT;

SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_36 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_37 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_38 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_39 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_8 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_40 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_41 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_42 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_43 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_44 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_45 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_46 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_47 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_48 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_49 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_30 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_32 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_50 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_35 :  STD_LOGIC;


BEGIN 
SYNTHESIZED_WIRE_3 <= '0';
SYNTHESIZED_WIRE_41 <= '1';
SYNTHESIZED_WIRE_42 <= '1';
SYNTHESIZED_WIRE_43 <= '1';
SYNTHESIZED_WIRE_44 <= '1';
SYNTHESIZED_WIRE_46 <= '1';
SYNTHESIZED_WIRE_47 <= '1';
SYNTHESIZED_WIRE_48 <= '1';
SYNTHESIZED_WIRE_49 <= '1';



SYNTHESIZED_WIRE_8 <= SYNTHESIZED_WIRE_0 AND SYNTHESIZED_WIRE_36;


SYNTHESIZED_WIRE_30 <= SYNTHESIZED_WIRE_37 XOR SYNTHESIZED_WIRE_38;


b2v_inst11 : sumador_completo
PORT MAP(A => SYNTHESIZED_WIRE_39,
		 B => SYNTHESIZED_WIRE_2,
		 Cin => SYNTHESIZED_WIRE_3,
		 S => SYNTHESIZED_WIRE_22,
		 Cout => SYNTHESIZED_WIRE_6);


b2v_inst12 : sumador_completo
PORT MAP(A => SYNTHESIZED_WIRE_39,
		 B => SYNTHESIZED_WIRE_5,
		 Cin => SYNTHESIZED_WIRE_6,
		 S => SYNTHESIZED_WIRE_25,
		 Cout => SYNTHESIZED_WIRE_40);


b2v_inst13 : sumador_completo
PORT MAP(A => SYNTHESIZED_WIRE_39,
		 B => SYNTHESIZED_WIRE_8,
		 Cin => SYNTHESIZED_WIRE_40,
		 S => SYNTHESIZED_WIRE_50,
		 Cout => SYNTHESIZED_WIRE_32);


SYNTHESIZED_WIRE_0 <= NOT(SYNTHESIZED_WIRE_38);



SYNTHESIZED_WIRE_35 <= SYNTHESIZED_WIRE_38 OR SYNTHESIZED_WIRE_37;



PROCESS(CK,SYNTHESIZED_WIRE_41,SYNTHESIZED_WIRE_41)
BEGIN
IF (SYNTHESIZED_WIRE_41 = '0') THEN
	SYNTHESIZED_WIRE_37 <= '0';
ELSIF (SYNTHESIZED_WIRE_41 = '0') THEN
	SYNTHESIZED_WIRE_37 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	SYNTHESIZED_WIRE_37 <= A0;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_42,SYNTHESIZED_WIRE_42)
BEGIN
IF (SYNTHESIZED_WIRE_42 = '0') THEN
	SYNTHESIZED_WIRE_38 <= '0';
ELSIF (SYNTHESIZED_WIRE_42 = '0') THEN
	SYNTHESIZED_WIRE_38 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	SYNTHESIZED_WIRE_38 <= A1;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_43,SYNTHESIZED_WIRE_43)
BEGIN
IF (SYNTHESIZED_WIRE_43 = '0') THEN
	SYNTHESIZED_WIRE_45 <= '0';
ELSIF (SYNTHESIZED_WIRE_43 = '0') THEN
	SYNTHESIZED_WIRE_45 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	SYNTHESIZED_WIRE_45 <= B0;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_44,SYNTHESIZED_WIRE_44)
BEGIN
IF (SYNTHESIZED_WIRE_44 = '0') THEN
	SYNTHESIZED_WIRE_36 <= '0';
ELSIF (SYNTHESIZED_WIRE_44 = '0') THEN
	SYNTHESIZED_WIRE_36 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	SYNTHESIZED_WIRE_36 <= B1;
END IF;
END PROCESS;


SYNTHESIZED_WIRE_19 <= SYNTHESIZED_WIRE_37 AND SYNTHESIZED_WIRE_45;


PROCESS(CK,SYNTHESIZED_WIRE_46,SYNTHESIZED_WIRE_46)
BEGIN
IF (SYNTHESIZED_WIRE_46 = '0') THEN
	r0 <= '0';
ELSIF (SYNTHESIZED_WIRE_46 = '0') THEN
	r0 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	r0 <= SYNTHESIZED_WIRE_19;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_47,SYNTHESIZED_WIRE_47)
BEGIN
IF (SYNTHESIZED_WIRE_47 = '0') THEN
	r1 <= '0';
ELSIF (SYNTHESIZED_WIRE_47 = '0') THEN
	r1 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	r1 <= SYNTHESIZED_WIRE_22;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_48,SYNTHESIZED_WIRE_48)
BEGIN
IF (SYNTHESIZED_WIRE_48 = '0') THEN
	r2 <= '0';
ELSIF (SYNTHESIZED_WIRE_48 = '0') THEN
	r2 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	r2 <= SYNTHESIZED_WIRE_25;
END IF;
END PROCESS;


PROCESS(CK,SYNTHESIZED_WIRE_49,SYNTHESIZED_WIRE_49)
BEGIN
IF (SYNTHESIZED_WIRE_49 = '0') THEN
	r3 <= '0';
ELSIF (SYNTHESIZED_WIRE_49 = '0') THEN
	r3 <= '1';
ELSIF (RISING_EDGE(CK)) THEN
	r3 <= SYNTHESIZED_WIRE_28;
END IF;
END PROCESS;








SYNTHESIZED_WIRE_39 <= SYNTHESIZED_WIRE_45 AND SYNTHESIZED_WIRE_38;




SYNTHESIZED_WIRE_2 <= SYNTHESIZED_WIRE_37 AND SYNTHESIZED_WIRE_36;


SYNTHESIZED_WIRE_5 <= SYNTHESIZED_WIRE_30 AND SYNTHESIZED_WIRE_36;


b2v_inst8 : band_c2
PORT MAP(Cout_2 => SYNTHESIZED_WIRE_40,
		 Cout_3 => SYNTHESIZED_WIRE_32,
		 A1 => SYNTHESIZED_WIRE_38,
		 B1 => SYNTHESIZED_WIRE_36,
		 r3 => SYNTHESIZED_WIRE_50,
		 V1 => V1,
		 V2 => V2);


SYNTHESIZED_WIRE_28 <= SYNTHESIZED_WIRE_50 AND SYNTHESIZED_WIRE_35;


END bdf_type;