-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Wed Oct 29 14:18:21 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY maq_de_estado IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        X : IN STD_LOGIC := '0'
    );
END maq_de_estado;

ARCHITECTURE BEHAVIOR OF maq_de_estado IS
    TYPE type_fstate IS (B2,B1,A1,U,C,B3,A2);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,X)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= C;
        ELSE
            CASE fstate IS
                WHEN B2 =>
                    reg_fstate <= U;
                WHEN B1 =>
                    reg_fstate <= B2;
                WHEN A1 =>
                    reg_fstate <= U;
                WHEN U =>
                    IF ((X = '0')) THEN
                        reg_fstate <= A2;
                    ELSIF ((X = '1')) THEN
                        reg_fstate <= B3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= U;
                    END IF;
                WHEN C =>
                    IF ((X = '1')) THEN
                        reg_fstate <= B1;
                    ELSIF ((X = '0')) THEN
                        reg_fstate <= A1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= C;
                    END IF;
                WHEN B3 =>
                    reg_fstate <= C;
                WHEN A2 =>
                    reg_fstate <= C;
                WHEN OTHERS => 
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
