-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Fri Oct 31 16:06:26 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY I2C IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        sda : IN STD_LOGIC := '0';
        fin_dir : IN STD_LOGIC := '0';
        soy : IN STD_LOGIC := '0';
        fin_dato : IN STD_LOGIC := '0';
        hab_dir : OUT STD_LOGIC;
        ack : OUT STD_LOGIC;
        hab_dat : OUT STD_LOGIC;
        E1 : OUT STD_LOGIC;
        E2 : OUT STD_LOGIC;
        E3 : OUT STD_LOGIC
    );
END I2C;

ARCHITECTURE BEHAVIOR OF I2C IS
    TYPE type_fstate IS (Guardar_dir,Oscioso,RW,AK,Guardar_dato);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,sda,fin_dir,soy,fin_dato)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= Oscioso;
            hab_dir <= '0';
            ack <= '0';
            hab_dat <= '0';
            E1 <= '0';
            E2 <= '0';
            E3 <= '0';
        ELSE
            hab_dir <= '0';
            ack <= '0';
            hab_dat <= '0';
            E1 <= '0';
            E2 <= '0';
            E3 <= '0';
            CASE fstate IS
                WHEN Guardar_dir =>
                    IF (((fin_dir = '1') AND (soy = '0'))) THEN
                        reg_fstate <= Oscioso;
                    ELSIF (((fin_dir = '1') AND (soy = '1'))) THEN
                        reg_fstate <= RW;
                    ELSIF ((fin_dir = '0')) THEN
                        reg_fstate <= Guardar_dir;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Guardar_dir;
                    END IF;

                    E3 <= '0';

                    E2 <= '0';

                    E1 <= '1';

                    hab_dat <= '0';

                    ack <= '0';

                    hab_dir <= '1';
                WHEN Oscioso =>
                    IF ((sda = '0')) THEN
                        reg_fstate <= Guardar_dir;
                    ELSIF ((sda = '1')) THEN
                        reg_fstate <= Oscioso;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Oscioso;
                    END IF;

                    E3 <= '0';

                    E2 <= '0';

                    E1 <= '0';

                    hab_dat <= '0';

                    ack <= '0';

                    hab_dir <= '0';
                WHEN RW =>
                    reg_fstate <= AK;

                    E3 <= '0';

                    E2 <= '1';

                    E1 <= '0';

                    hab_dat <= '0';

                    ack <= '0';

                    hab_dir <= '0';
                WHEN AK =>
                    reg_fstate <= Guardar_dato;

                    E3 <= '0';

                    E2 <= '1';

                    E1 <= '1';

                    hab_dat <= '0';

                    ack <= '1';

                    hab_dir <= '0';
                WHEN Guardar_dato =>
                    IF ((fin_dato = '1')) THEN
                        reg_fstate <= Oscioso;
                    ELSIF ((fin_dato = '0')) THEN
                        reg_fstate <= Guardar_dato;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Guardar_dato;
                    END IF;

                    E3 <= '1';

                    E2 <= '0';

                    E1 <= '0';

                    hab_dat <= '1';

                    ack <= '0';

                    hab_dir <= '0';
                WHEN OTHERS => 
                    hab_dir <= 'X';
                    ack <= 'X';
                    hab_dat <= 'X';
                    E1 <= 'X';
                    E2 <= 'X';
                    E3 <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
